name: codecov
on: [push]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Generate coverage report
        run: |
          go test `go list ./...` -coverprofile=coverage.txt -covermode=atomic

      - name: Upload coverage report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{ secrets.CODECOV }}
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella